# Match Detail Scraper

This notebook fetches HTML content from a basketball match detail page and displays the relevant tables in a tabular format.

## 1. Import Required Libraries

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

## 2. Fetch HTML Content from Match Detail URL

In [5]:
url = 'https://vblweb.wisseq.eu/Home/MatchDetail?wedguid=BVBL25269180ORBBSW%20%20CD'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
response = requests.get(url, headers=headers)
html_content = response.text
print(f'HTTP Status: {response.status_code}')

HTTP Status: 200

## 3. Parse HTML and Extract Tables

In [6]:
soup = BeautifulSoup(html_content, 'html.parser')
tables = soup.find_all('table')
print(f'Found {len(tables)} tables.')

Found 12 tables.

## 4. Display All Tables in Tabular Format

In [7]:
for idx, table in enumerate(tables):
    try:
        df = pd.read_html(str(table))[0]
        print(f'--- Table {idx+1} ---')
        display(df)
    except Exception as e:
        print(f'Could not parse table {idx+1}: {e}')

--- Table 1 ---

C:\Users\StijnHuysman\AppData\Local\Temp\ipykernel_28612\725879822.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Naam,Unnamed: 1,Geboortedatum,Cat,Lid sinds,Unnamed: 5
0,{{speler.volledigeNaam}},{{speler.volledigeNaam}},{{speler.mvo}},{{speler.gebdat}},{{speler.uCat}},{{speler.orgLMS}}

--- Table 2 ---

C:\Users\StijnHuysman\AppData\Local\Temp\ipykernel_28612\725879822.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Naam,Unnamed: 1,geboortedatum,Cat,Lid sinds
0,{{speler.volledigeNaam}},{{speler.mvo}},{{speler.gebdat}},{{speler.uCat}},{{speler.orgLMS}}

--- Table 3 ---

C:\Users\StijnHuysman\AppData\Local\Temp\ipykernel_28612\725879822.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

                                Naam
0  {{off.volledigeNaam}}{{off.Naam}}

--- Table 4 ---

C:\Users\StijnHuysman\AppData\Local\Temp\ipykernel_28612\725879822.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Unnamed: 0,Unnamed: 1,Rugnrs,Categorie,Naam,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,{{deelnemer.Fouten}},{{deelnemer.RugNr}} Cap,{{deelnemer.GebDat.substring(10)}},{{deelnemer.Naam}},NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Coach,Ass. Coach,Gedelegeerde,{{deelnemer.GebDat}},{{deelnemer.Naam}},NaN,"<"">",NaN,NaN

--- Table 5 ---

C:\Users\StijnHuysman\AppData\Local\Temp\ipykernel_28612\725879822.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Unnamed: 0,Unnamed: 1,Rugnrs,Categorie,Naam,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,{{deelnemer.Fouten}},{{deelnemer.RugNr}} Cap,{{deelnemer.GebDat.substring(10)}},{{deelnemer.Naam}},NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Coach,Ass. Coach,Gedelegeerde,{{deelnemer.GebDat}},{{deelnemer.Naam}},NaN,NaN,NaN,NaN

--- Table 6 ---

C:\Users\StijnHuysman\AppData\Local\Temp\ipykernel_28612\725879822.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Unnamed: 0,Naam,Reiskosten,Vergoeding,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,{{off.Functie}},{{off.Naam}},NaN,{{off.Reiskosten}},{{off.Vergoeding}},NaN,NaN

--- Table 7 ---

C:\Users\StijnHuysman\AppData\Local\Temp\ipykernel_28612\725879822.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,datum /tijd,filesize,Summary,filetype,maxindex,action
0,{{case.sDtCreation}},{{case.fileSize}},{{case.summary}},{{case.dwfFileType}},{{case.maxIndex}},Show file

--- Table 8 ---

C:\Users\StijnHuysman\AppData\Local\Temp\ipykernel_28612\725879822.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Periode,Time Out,Fouten,Punten
0,{{totalenTt.Periode}},{{totalenTt.TO}},{{totalenTt.Fouten}},{{totalenTt.Score}}

--- Table 9 ---

C:\Users\StijnHuysman\AppData\Local\Temp\ipykernel_28612\725879822.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Rnr,Naam,Unnamed: 2,Score
0,{{deelnemer.RugNr}},{{deelnemer.Naam}},{{deelnemer.Rol1e5}},{{deelnemer.iScore}}
1,{{deelnemer.RugNr}},{{deelnemer.Naam}},NaN,NaN

--- Table 10 ---

C:\Users\StijnHuysman\AppData\Local\Temp\ipykernel_28612\725879822.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Periode,Time Out,Fouten,Punten
0,{{totalenTu.Periode}},{{totalenTu.TO}},{{totalenTu.Fouten}},{{totalenTu.Score}}

--- Table 11 ---

C:\Users\StijnHuysman\AppData\Local\Temp\ipykernel_28612\725879822.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Rnr,Naam,Unnamed: 2,Score
0,{{deelnemer.RugNr}},{{deelnemer.Naam}},{{deelnemer.Rol1e5}},{{deelnemer.iScore}}
1,{{deelnemer.RugNr}},{{deelnemer.Naam}},NaN,NaN

--- Table 12 ---

C:\Users\StijnHuysman\AppData\Local\Temp\ipykernel_28612\725879822.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

       Official          Functie
0  {{off.Naam}}  {{off.Functie}}